// Full accuracy pipeline: renders tests/fixtures/a.docx with docx-renderer, its fork
// parent (docx-preview-sync), and the original docxjs project (docx-preview) inside
// benchmark/, screenshots each via agent-browser, scores every page against the
// Word-exported ground truth in real/a-page-*.png, then regenerates:
//   - accuracy/<library>/page-N-{reference,rendered,diff}.png
//   - accuracy/comparison-{light,dark}.svg
//   - ACCURACY.md        (full per-library, per-page report)
//   - README.md           (content between the ACCURACY marker comments only)
//
// Requires a Chrome binary for agent-browser (`pnpm exec agent-browser install`)
// and the pixel-diff devDependencies (pixelmatch, pngjs). Runs standalone in CI;
// see .github/workflows/accuracy.yml.
import { spawn, execFileSync } from 'node:child_process';
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { scoreRenderer } from './lib/pixel-diff.mjs';
import { renderComparisonChart } from './lib/comparison-chart.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const PORT = 5183;
const BASE_URL = `http://localhost:${PORT}/`;
const SCRATCH = fileURLToPath(new URL('../.accuracy-scratch', import.meta.url));

const RENDERERS = [
	{ value: 'docx-renderer', label: 'docx-renderer', title: 'docx-renderer (this project)', highlight: true },
	{ value: 'docx-preview-sync', label: 'docx-preview-sync', title: 'docx-preview-sync (fork parent)', highlight: false },
	{ value: 'docx-preview', label: 'docx-preview', title: 'docx-preview (docxjs, original)', highlight: false },
];

function ab(args) {
	const out = execFileSync('agent-browser', ['--json', ...args], { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
	const parsed = JSON.parse(out);
	if (parsed.success === false || parsed.error) {
		throw new Error(`agent-browser ${args.join(' ')} failed: ${parsed.error}`);
	}
	return parsed.data;
}

async function waitForServer(url, timeoutMs = 20000) {
	const start = Date.now();
	while (Date.now() - start < timeoutMs) {
		try {
			const res = await fetch(url);
			if (res.ok) return;
		} catch {
			// not up yet
		}
		await new Promise((r) => setTimeout(r, 250));
	}
	throw new Error(`benchmark server did not start within ${timeoutMs}ms`);
}

async function main() {
	mkdirSync(SCRATCH, { recursive: true });

	const server = spawn(
		'pnpm',
		['exec', 'vite', '--config', 'benchmark/vite.config.mjs', '--port', String(PORT), '--strictPort'],
		{ cwd: ROOT, stdio: 'ignore' },
	);

	try {
		await waitForServer(BASE_URL);
		ab(['open', BASE_URL]);
		ab(['set', 'viewport', '1240', '1754']);

		const runs = [];

		for (const renderer of RENDERERS) {
			ab([
				'eval',
				`(()=>{const el=document.querySelector('#renderer-select');el.value=${JSON.stringify(renderer.value)};el.dispatchEvent(new Event('change'));return true;})()`,
			]);
			ab(['wait', '--fn', "document.querySelector('#status').textContent.startsWith('done') || document.querySelector('#status').textContent.startsWith('error')"]);

			const state = ab([
				'eval',
				`(()=>{const status=document.querySelector('#status').textContent;const sections=Array.from(document.querySelectorAll('section')).map(s=>{const r=s.getBoundingClientRect();return {top:r.top+window.scrollY,left:r.left+window.scrollX,width:r.width,height:r.height};});return {status, sections};})()`,
			]).result;

			if (state.status.startsWith('error')) {
				throw new Error(`${renderer.label} failed to render: ${state.status}`);
			}

			const screenshotDir = `${SCRATCH}/${renderer.label}`;
			mkdirSync(screenshotDir, { recursive: true });
			const shot = ab(['screenshot', '--full', '--screenshot-dir', screenshotDir]);
			const screenshotPath = shot.path;

			const scored = scoreRenderer({
				renderedScreenshotPath: screenshotPath,
				sections: state.sections,
				realDir: `${ROOT}/real`,
				outDir: `${ROOT}/accuracy/${renderer.label}`,
			});

			runs.push({ ...renderer, ...scored });
			console.log(`${renderer.label}: ${(scored.overall * 100).toFixed(1)}% (${scored.pagesRendered} pages rendered)`);
		}

		renderComparisonChart(runs, `${ROOT}/accuracy`);
		writeAccuracyReport(runs);
		updateReadme(runs);
	} finally {
		server.kill();
		try {
			ab(['close']);
		} catch {
			// best-effort cleanup
		}
	}
}

function pct(n) {
	return `${(n * 100).toFixed(1)}%`;
}

function writeAccuracyReport(runs) {
	const lines = [
		'# Accuracy report',
		'',
		'Auto-generated by `pnpm measure:all` (`scripts/measure-all.mjs`). Do not edit by hand.',
		'',
		'Every library renders `tests/fixtures/a.docx` with `{ breakPages: true }` inside `benchmark/`, at viewport 1240×1754. Each rendered page is compared pixel-by-pixel against the corresponding page of `real/a-page-*.png`, rasterized from a PDF export of the same file produced by Microsoft Word (Microsoft 365). A library that renders fewer pages than the reference scores 0 for each missing page — the reference page count is the fixed denominator.',
		'',
		'## Summary',
		'',
		'| Library | Pages rendered | Overall score |',
		'|---|---|---|',
		...runs.map((r) => `| ${r.title} | ${r.pagesRendered} / ${r.results.length} | **${pct(r.overall)}** |`),
		'',
	];

	for (const run of runs) {
		lines.push(`## ${run.title}`, '');
		lines.push('| Page | Score |', '|---|---|');
		for (const r of run.results) {
			lines.push(`| ${r.page} | ${r.missing ? '0% (not rendered)' : pct(r.score)} |`);
		}
		lines.push('');
		for (const r of run.results) {
			if (r.missing) continue;
			lines.push(
				`### Page ${r.page} — ${pct(r.score)}`,
				'',
				`<p align="center">`,
				`  <img src="./accuracy/${run.label}/page-${r.page}-reference.png" width="30%" alt="Word reference, page ${r.page}">`,
				`  <img src="./accuracy/${run.label}/page-${r.page}-rendered.png" width="30%" alt="${run.title} output, page ${r.page}">`,
				`  <img src="./accuracy/${run.label}/page-${r.page}-diff.png" width="30%" alt="pixel diff, page ${r.page}">`,
				'</p>',
				'<p align="center"><sub>Word reference · rendered output · pixel diff</sub></p>',
				'',
			);
		}
	}

	writeFileSync(`${ROOT}/ACCURACY.md`, lines.join('\n'));
}

function updateReadme(runs) {
	const ours = runs.find((r) => r.label === 'docx-renderer');
	const showcasePage = ours.results.find((r) => r.page === 2);

	const block = [
		'<p align="center">',
		'  <picture>',
		'    <source media="(prefers-color-scheme: dark)" srcset="./accuracy/comparison-dark.svg">',
		'    <img src="./accuracy/comparison-light.svg" alt="Accuracy comparison: docx-renderer, docx-preview-sync, and docx-preview against a Word PDF export of a.docx">',
		'  </picture>',
		'</p>',
		'',
		`Representative page (page 2 of 5 — code block, image, table, text box) rendered by \`docx-renderer\`, scoring ${pct(showcasePage.score)}:`,
		'',
		'<p align="center">',
		'  <img src="./accuracy/docx-renderer/page-2-reference.png" width="30%" alt="Microsoft Word reference, page 2">',
		'  <img src="./accuracy/docx-renderer/page-2-rendered.png" width="30%" alt="docx-renderer output, page 2">',
		'  <img src="./accuracy/docx-renderer/page-2-diff.png" width="30%" alt="pixel diff, page 2">',
		'</p>',
		'<p align="center"><sub>Word reference · docx-renderer output · pixel diff</sub></p>',
		'',
		'Full per-page, per-library breakdown (all 5 pages × all 3 libraries, with reference/rendered/diff images): [`ACCURACY.md`](./ACCURACY.md).',
		'',
		'Methodology: `1 - (mismatched pixels / total pixels)` via [`pixelmatch`](https://github.com/mapbox/pixelmatch), scored against a Word PDF export (not a Word editing-view screenshot, so the diff reflects rendered output, not non-printing marks). Reproduce with `pnpm measure:all`.',
	].join('\n');

	const readmePath = `${ROOT}/README.md`;
	const readme = readFileSync(readmePath, 'utf8');
	const start = '<!-- ACCURACY:START -->';
	const end = '<!-- ACCURACY:END -->';
	const startIdx = readme.indexOf(start);
	const endIdx = readme.indexOf(end);
	if (startIdx === -1 || endIdx === -1) {
		throw new Error(`README.md is missing ${start} / ${end} markers`);
	}
	const updated = `${readme.slice(0, startIdx + start.length)}\n${block}\n${readme.slice(endIdx)}`;
	writeFileSync(readmePath, updated);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
